<?php
// Routes: /sites*
//   GET    /sites                          -> wo site list   (parsed table)
//   GET    /sites/{domain}/info            -> wo site info {domain}
//   POST   /sites                          -> wo site create {domain} {whitelisted flags}
//   DELETE /sites/{domain}                 -> wo site delete {domain} --no-prompt
//   POST   /sites/{domain}/enable          -> wo site enable {domain}
//   POST   /sites/{domain}/disable         -> wo site disable {domain}
//   POST   /sites/{domain}/cache/purge     -> wo site update {domain} --purge-cache

// Emit JSON + exit.
function sites_out(array $data, int $code = 200): void {
    http_response_code($code);
    echo json_encode($data);
    exit;
}

// Parse `wo site list` output into Site[].
// Handles the bordered ASCII table (header-mapped, order-independent); falls
// back to plain one-domain-per-line output. ssl is not in list output -> false.
function parse_site_list(string $out): array {
    $lines = preg_split('/\r?\n/', $out);
    $rows = [];
    $header = null;

    foreach ($lines as $line) {
        $t = trim($line);
        if ($t === '' || $t[0] === '+') continue;          // skip blanks + separators
        if (!str_contains($t, '|')) {
            // plain-list fallback: a bare domain token
            if (preg_match('/^[a-zA-Z0-9.\-]+$/', $t)) {
                $rows[] = ['domain' => $t, 'type' => '', 'php' => '', 'cache' => '', 'ssl' => false, 'status' => 'enabled'];
            }
            continue;
        }
        // split a table row "| a | b | c |" into trimmed cells
        $cells = array_map('trim', explode('|', trim($t, '| ')));
        if ($header === null) {
            $header = array_map(fn($h) => strtolower($h), $cells);
            continue;
        }
        $row = [];
        foreach ($cells as $i => $v) $row[$header[$i] ?? $i] = $v;
        $status = strtolower($row['status'] ?? '');
        $rows[] = [
            'domain' => $row['site'] ?? ($row['domain'] ?? ''),
            'type'   => $row['type'] ?? '',
            'php'    => $row['php'] ?? '',
            'cache'  => $row['cache'] ?? '',
            'ssl'    => false,
            'status' => str_starts_with($status, 'enable') ? 'enabled' : 'disabled',
        ];
    }
    return array_values(array_filter($rows, fn($r) => $r['domain'] !== ''));
}

// Parse `wo site info {domain}` key:value lines into a map.
// `wo site info` is TAB/multi-space aligned, e.g.:
//   "Nginx configuration\t php basic (enabled)"
//   "PHP Version\t\t 8.3"
// Key and value are separated by a tab or 2+ spaces; skip the header + blanks.
function parse_site_info(string $out): array {
    $info = [];
    foreach (preg_split('/\r?\n/', $out) as $line) {
        $line = rtrim($line);
        $t = trim($line);
        if ($t === '' || stripos($t, 'Information about') === 0) continue;
        $cols = preg_split('/\t+|\s{2,}/', $t, 2);
        if (count($cols) === 2) {
            $k = trim($cols[0]);
            if ($k !== '') $info[$k] = trim($cols[1]);
        }
    }
    return $info;
}

function handle_sites(string $method, array $parts): void {
    $domain = $parts[1] ?? '';
    $sub    = $parts[2] ?? '';

    // collection-level: /sites
    if ($domain === '') {
        if ($method === 'GET') {
            $r = wo_exec(['site', 'list']);
            $sites = parse_site_list($r['output']);
            // wo failed AND nothing parsed -> surface the error instead of an empty table
            if (!$r['ok'] && count($sites) === 0) {
                sites_out(cmd_response($r, ['sites' => []]), 500);
            }
            sites_out(['sites' => $sites, 'output' => $r['output']]);
        }
        if ($method === 'POST') {
            $body = json_decode((string) file_get_contents('php://input'), true) ?? [];
            $args = build_create_args($body);            // validates + 400s on bad input
            $r = wo_exec($args);
            // wo create can exit nonzero on partial steps; trust the explicit success
            // line, and treat WordOps' "serious error" banner as a hard failure.
            $success = str_contains($r['output'], 'Successfully created site');
            $failed  = stripos($r['output'], 'serious error') !== false
                    || stripos($r['output'], 'error encountered') !== false;
            $ok = $success || ($r['ok'] && !$failed);
            if ($ok) {
                // surface the WP admin user/password (generated by WordOps, or the
                // ones the user supplied) so the UI can show them once.
                sites_out(['ok' => true, 'output' => $r['output']] + parse_wp_credentials($r['output']));
            }
            sites_out(cmd_response(['ok' => false, 'output' => $r['output'], 'code' => $r['code']]), 500);
        }
        sites_out(['error' => 'Method not allowed'], 405);
    }

    // item-level: domain required + validated
    $domain = validate_domain($domain);

    // DELETE /sites/{domain}
    if ($sub === '' && $method === 'DELETE') {
        $r = wo_exec(['site', 'delete', $domain, '--no-prompt']);
        sites_out(cmd_response($r), $r['ok'] ? 200 : 500);
    }

    // GET /sites/{domain}/info
    if ($sub === 'info' && $method === 'GET') {
        $r = wo_exec(['site', 'info', $domain]);
        if (!$r['ok']) sites_out(cmd_response($r, ['info' => []]), 500);
        sites_out(['info' => parse_site_info($r['output']), 'output' => $r['output']]);
    }

    // POST /sites/{domain}/enable
    if ($sub === 'enable' && $method === 'POST') {
        $r = wo_exec(['site', 'enable', $domain]);
        sites_out(cmd_response($r), $r['ok'] ? 200 : 500);
    }

    // POST /sites/{domain}/disable
    if ($sub === 'disable' && $method === 'POST') {
        $r = wo_exec(['site', 'disable', $domain]);
        sites_out(cmd_response($r), $r['ok'] ? 200 : 500);
    }

    // POST /sites/{domain}/cache/purge
    // WordOps has no per-site purge flag; `wo clean --all` flushes all caches.
    // It RESTARTS Nginx (~12s), which would drop this very request, so run it
    // detached and return immediately.
    if ($sub === 'cache' && ($parts[3] ?? '') === 'purge' && $method === 'POST') {
        wo_exec_detached(['clean', '--all']);
        sites_out(['ok' => true, 'output' => 'Cache purge started (FastCGI, opcache, Redis). Nginx will reload.']);
    }

    sites_out(['error' => 'Not found'], 404);
}
